
@channelToken = 7S+UcDkjdX6VgYEJAB4RfYFhCEqRcD4cnq7R3gy4pLRACo7rAprKdtiWzMEC1GESF1QLCYSEEFoAnpGj/C79jT7zMq1PyO9jMdkTYsC/QSALwN9IVAIw48OBxaDaMdMQTQgTdp8x34ODNRX9UzXN/QdB04t89/1O/w1cDnyilFU=
### Get bot information
GET https://api.line.me/v2/bot/info
Content-Type: application/json
Authorization: Bearer {{channelToken}}

# {
#   "userId": "U5f0825ebf352f18a4b203186173ffb28",
#   "basicId": "@981mtiti",
#   "displayName": "mychannelname1",
#   "chatMode": "bot",
#   "markAsReadMode": "auto"
# }