@userToken = eyJraWQiOiI1Y2VlMzdlNjljMzUzNzY2YTNmZTAxZmEwNWJmODIxMjgzNTQxYTg0YTY2OTJjZGVkZGY5NDdkMGMwOTA0MzY3IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2FjY2Vzcy5saW5lLm1lIiwic3ViIjoiVTEzMDQxN2NjM2NhZmY3NjQzZmRiNGI5ZWYxYmMyZTNlIiwiYXVkIjoiMjAwMDA2OTUyOCIsImV4cCI6MTY5MDM1OTIzNiwiaWF0IjoxNjkwMzU1NjM2LCJhbXIiOlsibGluZXNzbyJdLCJuYW1lIjoiS2jDoW5oIFbFqSBycnIiLCJwaWN0dXJlIjoiaHR0cHM6Ly9wcm9maWxlLmxpbmUtc2Nkbi5uZXQvMGhNUjRhV2xVdUVuMEpHQURhdVp0dEtqVmRIQkItTmhRMWNYWllTQ3NRVHg1M2ZBQl9aWHRmRXk5S1RVZ2plbFl2TkhoZUV5OGNUVWtzIn0.OtwckQ4d7_ui66xPSIIZCz-I3pdKYBcWl_Qjy2UTJwi1h_iyFi8NZjyCD3BYrU1cHIzrgfafh1CCslEjFDHirQ
@clientId =2000069528
@userAccessToken = eyJhbGciOiJIUzI1NiJ9.RsSPYGCgkz6O5VSCSxzFcCxm3bIYJHOsYLHfx3aqgQtK0kkCo5j5uY7Sx_ZwdUVuzBRfN8i1bIprojsel71LTJej6UF2Qdfc-ybquPE6uv739JLGgXQDcfQX_WATpzvcS2KBgPu36g3UM5G9p20IXdtRcNxRpQln2JbYnZZ0V9g.JLugeKZ7IFI4BBnheA0UHthNhYgKT61TIt6mjN3Aroc
@userId = U130417cc3caff7643fdb4b9ef1bc2e3e
@channelToken = 
### Get profile userToken have expire time 1h, dont' have user id
POST https://api.line.me/oauth2/v2.1/verify
Content-Type: application/x-www-form-urlencoded

id_token={{userToken}}&client_id={{clientId}}




### AccessToken: Verify accessToken from liff.getAccessToken
GET https://api.line.me/oauth2/v2.1/verify?access_token={{userAccessToken}}

### Method 1: AccessToken - Get user profile: scope profile
GET https://api.line.me/v2/profile
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

### AccessToken: Get user information: scrop openid
GET https://api.line.me/oauth2/v2.1/userinfo
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}


### method 2: Get user profile by channel token
GET https://api.line.me/v2/bot/profile/{{userId}}
Content-Type: application/json
Authorization: Bearer {{channelToken}}

