# after login, and call liff.getIDToken();
@userToken = eyJraWQiOiJhMmE0NTlhZWM1YjY1ZmE0ZThhZGQ1Yzc2OTdjNzliZTQ0NWFlMzEyYmJjZDZlZWY4ZmUwOWI1YmI4MjZjZjNkIiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2FjY2Vzcy5saW5lLm1lIiwic3ViIjoiVTMzZmU5MWNmYjc0ZDI3Y2UyZTdjNzIxMDJhOGZmYWU1IiwiYXVkIjoiMjAwMDA2OTUyOCIsImV4cCI6MTY5MDM2NzM0MiwiaWF0IjoxNjkwMzYzNzQyLCJhbXIiOlsibGluZXNzbyJdLCJuYW1lIjoiZGF0MTIzIiwicGljdHVyZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoVlZzQmlZNTlDWGxPT3h1d0pTeDJMbkotQnhRNUZROHhObFVXR1c0NVVVRTJXMDU3ZWx3UlNHbHNWVTVsWEJwNmRGNFVGenM0Vng1ZyJ9.Lzujw868ti9VgzgceR6I-C6rvS4HNmCcmjC5hWOeRqlk_Qw_v57bByryyPGkwZkTDHbDFQwuE-JhaQW_orp8NQ

# from channel login, get channel ID 2000069528
@clientId =2000069528

### Get profile userToken have expire time 1h, dont' have user id
POST https://api.line.me/oauth2/v2.1/verify
Content-Type: application/x-www-form-urlencoded

id_token={{userToken}}&client_id={{clientId}}

####
# after login, get from call liff.getAccessToken();
@userAccessToken = eyJhbGciOiJIUzI1NiJ9.YEh3i-SBE0tN6XAomjI8yrHGLEuZVkXswp-yMaSYEiVmsVup_tY6U8jneyvBw9og0FF_hFTwFrZfB9Hg6ZQGJSGQADJ1gpyJ4ma5eM2MipyjKxub9xEFOyNE3YoLhHj7niTpIXUw9PXrLGarbNgN1hI8tgVyBWTdeoREzro7SEs.2zJ_Nzkbfoe6nohA3wDBrBx95o5IJMZDA6ewON97omE
# after glogin, get from call liff.getProfile();
@userId = U33fe91cfb74d27ce2e7c72102a8ffae5
# get from channel message, https://developers.line.biz/console/channel/2000088084/messaging-api
@channelToken = FZ9q78ZqxOCLwPv0/BOtFQU8z/MGTPVwXyenesRaP0cnNqU/7/4zgYjN+4dh7DNW8tPCQ5xhl0OYrsKRbvSKNisFYaQiMZilaKNhtywOB7CBbo/lj8/Ak2ceYOLFJ6ZEmvKly8bT3cTtNkPQnY6oRAdB04t89/1O/w1cDnyilFU=


### AccessToken: Verify accessToken from liff.getAccessToken
GET https://api.line.me/oauth2/v2.1/verify?access_token={{userAccessToken}}

### Method 1: AccessToken - Get user profile: scope profile
GET https://api.line.me/v2/profile
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

### AccessToken: Get user information: scrop openid
GET https://api.line.me/oauth2/v2.1/userinfo
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}


### method 2: Get user profile by channel token
GET https://api.line.me/v2/bot/profile/{{userId}}
Content-Type: application/json
Authorization: Bearer {{channelToken}}

