# after login, and call liff.getIDToken();
@userToken = eyJraWQiOiI1Y2VlMzdlNjljMzUzNzY2YTNmZTAxZmEwNWJmODIxMjgzNTQxYTg0YTY2OTJjZGVkZGY5NDdkMGMwOTA0MzY3IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2FjY2Vzcy5saW5lLm1lIiwic3ViIjoiVTRkNDU5MzRlNmI2ZjhjZDM0MzQ1NDBiOTAzMmYzNzM5IiwiYXVkIjoiMjAwMDc5MzAzMiIsImV4cCI6MTY5NDk0MTI3MSwiaWF0IjoxNjk0OTM3NjcxLCJhbXIiOlsibGluZXNzbyJdLCJuYW1lIjoiZGF0ZGFvIiwicGljdHVyZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoVlZzQmlZNTlDWGxPT3h1d0pTeDJMbkotQnhRNUZROHhObFVXR1c0NVVVRTJXMDU3ZWx3UlNHbHNWVTVsWEJwNmRGNFVGenM0Vng1ZyJ9.VEi53Y23k1_N1pqW_70fL0-b8h-uflIL2Xebu9CYPvaf2b-EUMQOOBS9UIKEXaXqTG0r3JlszuVnkCr1eQji9Q

# from channel login, get channel ID 2000069528
@clientId =2000793032

### Get profile userToken have expire time 1h, dont' have user id
POST https://api.line.me/oauth2/v2.1/verify
Content-Type: application/x-www-form-urlencoded

id_token={{userToken}}&client_id={{clientId}}

####
# after login, get from call liff.getAccessToken();
@userAccessToken = eyJhbGciOiJIUzI1NiJ9.4Ts9hJcLjbqa9Nr0WsA7j5joyPk0gtC45xbvpOXgTp8Id1-8Om5666VBGF387N37Fi7cGo56cBkEbAch4xn_FLJAMcU0JBmu7LSA-sAychx-1c9NfB6PQxx8zr_ZJo7OKtvRtZreK8nQVwLQTe0uvQWzvFNKbXyEhA7iG4tIkCE.kt01MAYUeS2ZHBPLGmzd6YGQaeHf2eOes2jTGPj_Tws
# after glogin, get from call liff.getProfile();
@userId = U4d45934e6b6f8cd3434540b9032f3739
# get from channel message, https://developers.line.biz/console/channel/2000792273/messaging-api
@channelToken = 7S+UcDkjdX6VgYEJAB4RfYFhCEqRcD4cnq7R3gy4pLRACo7rAprKdtiWzMEC1GESF1QLCYSEEFoAnpGj/C79jT7zMq1PyO9jMdkTYsC/QSALwN9IVAIw48OBxaDaMdMQTQgTdp8x34ODNRX9UzXN/QdB04t89/1O/w1cDnyilFU=


### AccessToken: Verify accessToken from liff.getAccessToken
GET https://api.line.me/oauth2/v2.1/verify?access_token={{userAccessToken}}

### Method 1: AccessToken - Get user profile: scope profile
GET https://api.line.me/v2/profile
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}

### AccessToken: Get user information: scrop openid
GET https://api.line.me/oauth2/v2.1/userinfo
Content-Type: application/json
Authorization: Bearer {{userAccessToken}}


### method 2: Get user profile by channel token
GET https://api.line.me/v2/bot/profile/{{userId}}
Content-Type: application/json
Authorization: Bearer {{channelToken}}

