

@userToken = eyJraWQiOiI1Y2VlMzdlNjljMzUzNzY2YTNmZTAxZmEwNWJmODIxMjgzNTQxYTg0YTY2OTJjZGVkZGY5NDdkMGMwOTA0MzY3IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJpc3MiOiJodHRwczovL2FjY2Vzcy5saW5lLm1lIiwic3ViIjoiVTRkNDU5MzRlNmI2ZjhjZDM0MzQ1NDBiOTAzMmYzNzM5IiwiYXVkIjoiMjAwMDc5MzAzMiIsImV4cCI6MTY5NDk0MTI3MSwiaWF0IjoxNjk0OTM3NjcxLCJhbXIiOlsibGluZXNzbyJdLCJuYW1lIjoiZGF0ZGFvIiwicGljdHVyZSI6Imh0dHBzOi8vcHJvZmlsZS5saW5lLXNjZG4ubmV0LzBoVlZzQmlZNTlDWGxPT3h1d0pTeDJMbkotQnhRNUZROHhObFVXR1c0NVVVRTJXMDU3ZWx3UlNHbHNWVTVsWEJwNmRGNFVGenM0Vng1ZyJ9.VEi53Y23k1_N1pqW_70fL0-b8h-uflIL2Xebu9CYPvaf2b-EUMQOOBS9UIKEXaXqTG0r3JlszuVnkCr1eQji9Q


@clientId =2000793032
@userAccessToken = eyJhbGciOiJIUzI1NiJ9.4Ts9hJcLjbqa9Nr0WsA7j5joyPk0gtC45xbvpOXgTp8Id1-8Om5666VBGF387N37Fi7cGo56cBkEbAch4xn_FLJAMcU0JBmu7LSA-sAychx-1c9NfB6PQxx8zr_ZJo7OKtvRtZreK8nQVwLQTe0uvQWzvFNKbXyEhA7iG4tIkCE.kt01MAYUeS2ZHBPLGmzd6YGQaeHf2eOes2jTGPj_Tws
@userId = U4d45934e6b6f8cd3434540b9032f3739
@channelToken = 7S+UcDkjdX6VgYEJAB4RfYFhCEqRcD4cnq7R3gy4pLRACo7rAprKdtiWzMEC1GESF1QLCYSEEFoAnpGj/C79jT7zMq1PyO9jMdkTYsC/QSALwN9IVAIw48OBxaDaMdMQTQgTdp8x34ODNRX9UzXN/QdB04t89/1O/w1cDnyilFU=
### Verify webhook setup
POST https://api.line.me/v2/bot/channel/webhook/test
Content-Type: application/json
Authorization: Bearer {{channelToken}}


### Sending reply message
@replyTokenx = 884b1eaf3f044db5a3d601694f668b9a
POST https://api.line.me/v2/bot/message/reply
Content-Type: application/json
Authorization: Bearer {{channelToken}}

{
    "replyToken": "{{replyTokenx}}",
    "messages":[
        {
            "type":"text",
            "text":"What are you typing?1"
        },
        {
            "type":"text",
            "text":"What are you typing?2"
        }
    ]
}

### Sending push message

#random 16
@randomKey = a8371f5c-2b98-11ee-be56-0242ac120004
POST https://api.line.me/v2/bot/message/push
Content-Type: application/json
Authorization: Bearer {{channelToken}}
X-Line-Retry-Key: {{randomKey}}

{
    "to": "{{userId}}",
    "messages":[
        {
            "type":"text",
            "text":"Hello, I am Dat"
        },
        {
            "type":"text",
            "text":"May I help you with my power1"
        }
    ]
}

#####
curl -v -X POST https://api.line.me/v2/bot/message/multicast \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer {{channelToken}}' \
-H 'X-Line-Retry-Key: {{$guid}}' \
-d '{
    "to": ["U4d45934e6b6f8cd3434540b9032f3739"],
    "messages":[
        {
            "type":"text",
            "text":"Hello, world1"
        },
        {
            "type":"text",
            "text":"Hello, world2"
        }
    ]
}'

######
#random 16
@randomKey = a8371f5c-2b98-11ee-be56-0242ac120006
POST https://api.line.me/v2/bot/message/push
Content-Type: application/json
Authorization: Bearer {{channelToken}}
X-Line-Retry-Key: {{randomKey}}

{
    "to": "{{userId}}",
    "messages":[
        {
		"type" : "template",
		"altText" : "クレジットカード認証エラー",
		"template" : {
			"type" : "buttons",
			"text" : "変更が完了したら以下の「変更完了」ボタンを押してください。",
			"actions" : [
				{
					"type" : "postback",
					"data" : "{\"data\":\"64febd9d18e43db82cbbc1fe\",\"type\":\"card_add_error\"}",
					"label" : "「変更完了」"
				}
			]
		}
	}
    ]
}
